# Generated by Django 3.0.5 on 2020-05-24 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200524_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='Attendence',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='Salary',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='status',
            field=models.CharField(choices=[('onduty', 'onduty'), ('offduty', 'offduty')], default=0, max_length=300),
            preserve_default=False,
        ),
    ]
