# Generated by Django 3.0.5 on 2020-05-24 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200524_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoices',
            name='Outstanding',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
